name: 'Dependency Review'
on: [pull_request]
permissions:
  contents: read
  pull-requests: write
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: Dependency Review
        uses: actions/dependency-review-action@v3.0.6
        with:
          fail-on-severity: high
          # Use comma-separated names to pass list arguments:
          deny-licenses: LGPL-2.0, AGPL-1.0-or-later, AGPL-3.0-or-later
          comment-summary-in-pr: true
